Add wordpress md5 verification

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -14,7 +14,23 @@ install_dir=${OPENSHIFT_DATA_DIR}${install_version}
 mkdir -p ${install_dir}
 
 pushd ${install_dir} >/dev/null
-curl -s http://wordpress.org/wordpress-${install_version}.tar.gz | tar --strip-components=1 -xzf -
+curl -s http://wordpress.org/wordpress-${install_version}.tar.gz > wordpress-${install_version}.tar.gz
+
+# Verify the sources
+#
+tarball_md5=$(md5sum wordpress-${install_version}.tar.gz | cut -d ' ' -f 1)
+wordpress_md5=$(curl -s http://wordpress.org/wordpress-${install_version}.tar.gz.md5)
+
+if [ "${tarball_md5}" != "${wordpress_md5}" ]; then
+  echo "ERROR: Wordpress ${install_version} MD5 checksum mismatch."
+  exit 1;
+fi
+
+# Install Wordpress
+#
+tar --strip-components=1 -xzf wordpress-${install_version}.tar.gz
+rm -rf wordpress-${install_version}.tar.gz
+
 popd >/dev/null
 
 ln -sf ${install_dir} ${OPENSHIFT_DATA_DIR}current
